trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

variables:
- group: kuiper2.0_group_variables
- ${{ if eq(variables['Build.Reason'], 'PullRequest')}}:
  - name: branch
    value: $[replace(variables['System.PullRequest.TargetBranch'], 'refs/heads/', '')]
- ${{ else }}:
  - name: branch
    value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

jobs:
- job: Kuiper
  strategy:
    matrix:
      ${{if true }}:
        '32bit basic':
          group_var: 'KUIPER_BASIC_32'
          artifact_name: 'kuiper_volume_basic_32'
        '64bit basic':
          group_var: 'KUIPER_BASIC_64'
          artifact_name: 'kuiper_volume_basic_64'
      ${{ if ne(variables['Build.Reason'], 'PullRequest')}}:
        '32bit full':
          group_var: 'KUIPER_FULL_32'
          artifact_name: 'kuiper_volume_full_32'
        '64bit full':
          group_var: 'KUIPER_FULL_64'
          artifact_name: 'kuiper_volume_full_64'
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 200
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      sudo apt-get install -y qemu-user-static
      branch_name=$(echo $(branch) | tr 'a-z' 'A-Z' | sed 's/[^[:alnum:]]/_/g')
      # var_name stores the name of a variabile which is defined in the group variable
      # is accessed by indirect expansion of the environment variable which is exported from the group
      var_name="$(group_var)_$branch_name"
      ci/modify_config.sh ./config "${!var_name}"
      sudo bash build-docker.sh
      ls kuiper-volume/*.zip >/dev/null 2>&1 && exit 0 || exit 2
    displayName: 'Build image'
  - task: PublishPipelineArtifact@1
    condition: true
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/kuiper-volume'
      artifact: $(artifact_name)
      publishLocation: 'pipeline'
